### ISSUE TITLE
Latest release flooding chat with garbage flips

### ISSUE THREAD

**Issue by Barragek0** [mindlesslydev/NotEnoughCoins#10]
![image](https://user-images.githubusercontent.com/24503018/136736749-03575543-9f2a-485c-8ddf-2a72cd80b529.png)

**Comment by mindlesslydev** [comment]
Perhaps, but note it is only pulling one page of the auction house per cycle. I don’t think that should be too bad?

**Comment by mindlesslydev** [comment]
I could do something like that - will plan it out later
