### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by RobotHanzo** [mindlesslydev/NotEnoughCoins#21]
I believe that the mod would look good in a form of a GUI, including settings and flippable items
There are a two ways to implement them:
1. Custom code (Very complicated and can be extremely ugly)
2. Use existing libraries (ex. Essentials)

@mindlesslydev Please provide some opinions

**Comment by mindlesslydev** [comment]
I think sliders for the options aside from entering the API key could be quite nice. We could also display the auction items in a GUI with information etc

**Comment by RobotHanzo** [comment]
How about the method? Would you be fine with using 3rd party libraries

**Comment by mindlesslydev** [comment]
Yes, would save a lot of time

**Comment by RobotHanzo** [comment]
https://github.com/mindlesslydev/NotEnoughCoins/pull/37
