### ISSUE TITLE
Offsite blacklist?

### ISSUE THREAD

**Issue by Praxtical** [mindlesslydev/NotEnoughCoins#24]
It seems tedious to update the mod every time the blacklist is updated, could it be possible to store the blacklist file on a server and get the blacklist from that server to allow for input-less updates?

**Comment by mindlesslydev** [comment]
I wouldn’t usually do that, it was just that there was one item that was becoming a burden for a lot of users and the first time I attempted to blacklist it for whatever reason it still managed to bypass the check so I had to take other messages. As for storing it on an external server, I’m not paying for that lol
