### ISSUE TITLE
Fix auctions being sometimes old and already sold

### ISSUE THREAD

**Issue by StarL0st** [mindlesslydev/NotEnoughCoins#27]
So sometimes when flips appear in chat they are already sold, so sometimes it makes it hard to catch a good deal, I have speed 4 (a pretty decent one) 
It will be nice to have it fixed, I think that you could change to oficial Hypixel API and redo the way you look for auctions

Thanks for your time!

Forgot to say that even sometimes profit is broken, it shows me a 3.9m spirit boots when the lowest BIN is 3m

**Comment by mindlesslydev** [comment]
Hi, so auctions are checked with the official Hypixel API. They are also removed near immediately after they have sold. Unfortunately, items are bought out so fast by people macroing this mod that it would pretty challenging to remove them from the list before this happens. I can look into a solution, however it only updates as fast as a) Hypixel API and b) the method

**Comment by StarL0st** [comment]
I get it, is there a way to avoid macroing?, like add a delay for everytime they click the message?

**Comment by StarL0st** [comment]
also forgot to bump the problem of profit, seems to have some flaws

**Comment by mindlesslydev** [comment]
In terms of macroing, the issue is more about people editing my code and turning it into an automated script.
The profit issue I will need to look into, but generally speaking if you look on the auction house that 3m one or whatever should be gone already
