### ISSUE TITLE
Discord Invite Link

### ISSUE THREAD

**Issue by zZagro** [mindlesslydev/NotEnoughCoins#30]
Hey,
I wanted to join the Discord but it looks like, that the Discord link on the main page is not working anymore.
It would be good if you put an unlimited use Link on The page.
Thanks

**Comment by DarkShadow19** [comment]
i need it too

**Comment by mindlesslydev** [comment]
This is intentional, we purged invites earlier as someone was attempting to raid the server. Invites will be reopened soon.

**Comment by zZagro** [comment]
> This is intentional, we purged invites earlier as someone was attempting to raid the server. Invites will be reopened soon.

Oh, ok. Thank you for the fast reply ^^
