### ISSUE TITLE
high internet usage

### ISSUE THREAD

**Issue by Treppenhaus** [mindlesslydev/NotEnoughCoins#32]
As soon as i start minecraft with the mod and join hypixel, my internet pretty much dies
here are some screenshots

![Image](https://i.uwu.bz/BWcyhsigs7.png?key=SN1cI8Lyermbcw)

The first sequence is when I started Minecraft,  the second sequence when i joined hypixel.
25 MB/s is pretty much all my internet can handle, so I disconnected multiple times from hypixel.

its not impossible to play like that

**Comment by Erisfiregamer1** [comment]
This is probably because it has to:
- Connect to the API
- Do constant checks for underpriced items
- Notify the user
This would take up a lot of bandwidth, no?
