### ISSUE TITLE
Other flipping methods

### ISSUE THREAD

**Issue by Praxtical** [mindlesslydev/NotEnoughCoins#35]
Would it be possible to figure out good crafting/enchanting flips?
eg compare raw craft cost to lowest bin and suggest the ones with the highest gaps relative to the cost of the item
compare the cost of 16 level 1 books to 1 level 5 book and suggest the ones with the highest gaps relative to the cost of the item

if you are working on other important stuff for the mod I would love to help contribute and attempt to make it myself
(new at programming in java and looking for every opportunity!)

**Comment by mindlesslydev** [comment]
This is definitely something quite far down the to do list. If you would like to contribute, feel free. I appreciate all the help I can get and this would definitely help get towards the holy grail of release 1.0 sooner rather than later lol
